## Creating html file list

In [1]:
import pandas as pd

In [2]:
import os
file_list = [f for f in os.listdir('htmls') if f.endswith(".html")]
len(file_list)
print(file_list)

['citility.html', 'poligma.html', 'voxcracy.html', 'LLL_2.html', 'bluenove.html', 'ecivis.html', 'make4.html', 'civimetric.html', 'voteetvous.html', 'vooter.html', 'organigram_97.html', 'forcity_mere.html', 'mymairie.html', 'quorum.html', 'fullmobs.html', 'mairesetcitoyens.html', 'parlonspo.html', 'make3.html', 'consultvox.html', 'loomio.html', 'politiker.html', 'citizenlabbv.html', 'datagora.html', 'ouiville.html', 'forcity.html', 'accromedias.html', 'lesbricodeurs.html', 'crowdpac.html', 'ledrenche.html', 'youvote.html', 'make2.html', 'ecreall_nova_ideo.html', 'neocity.html', 'citieszen.html', 'politicus.html', 'capcollectif.html', 'whip.html', 'voxestudio.html', 'democracyos.html', 'polipart.html', 'LLL.html', 'hacktiv.html', 'voxpublic.html', 'citybay_ambitions.html', 'politizr.html', 'digitalebox.html', 'mesopinions.html', 'assemblee_virtuelle.html', 'madeinvote.html', 'wesignit.html', 'mieuxvoter.html', 'kawaa.html', 'ciwik.html', 'data_for_good.html', 'digiworks.html', 'equivote_myopencity.html', 'make.html', 'kohero.html', 'openagora.html', 'moneparti.html', 'nousrassemble.html', 'bittle.html', 'marston_massiet.html', 'democratieouverte.html', 'koom.html', 'purpoz.html', 'reperage_urbain.html', 'regardscitoyens.html', 'D21.html', 'IDcity.html', 'Stig.html', 'opensourcepolitics.html', 'GOV.html', 'veritepol.html', 'fluicity.html', 'civocracy.html']

## Importing htmls into dictionary

In [3]:
capco= pd.read_html("htmls/capcollectif.html")

In [4]:
capco

[              0                                                  1
 0     Adresse :               25 RUE CLAUDE TILLIER 75012 PARIS 12
 1    Activité :          Édition de logiciels système et de réseau
 2    Effectif :             Entre 20 et 49 salariés  (donnée 2020)
 3    Création :                                         16/05/2014
 4  Dirigeants :  Cyril Pereira Lage, KARILA AUDIT ET CONSEIL, F...,
                       0                                            1
 0               SIREN :                                  803 377 571
 1       SIRET (siège) :                            803 377 571 00036
 2     Forme juridique :          SAS, société par actions simplifiée
 3        Numéro de TVA:                                FR12803377571
 4  Inscription au RCS :  INSCRIT (au greffe de PARIS, le 08/07/2014)
 5          Numéro RCS :                     803 377 571 R.C.S. Paris
 6      Capital social :                                  14 000,00 €,
                                         0  \
 0          Activité principale déclarée :
 1                       Code NAF ou APE :
 2                    Domaine d’activité :
 3              Conventions collectives  :
 4  Date de clôture d'exercice comptable :

                                                    1
 0  Conception, réalisation et diffusion de tout p...
 1  58.29A (Édition de logiciels système et de rés...
 2                                            Édition
 3  IDCC 9999  Bureaux d'études techniques, des ca...
 4                                         31/12/2023  ,
                             Performance   2020    2019    2018   2017
 0                Chiffre d'affaires (€)  1,93M   2,38M    1,5M   840K
 1                       Marge brute (€)  1,93M   2,38M    1,5M   849K
 2                      EBITDA - EBE (€)  -178K    117K  -67,9K  2,47K
 3           Résultat d'exploitation (€)  -211K   71,2K  -84,9K  2,29K
 4                      Résultat net (€)  -134K    148K   8,46K  68,4K
 5                            Croissance   2020    2019    2018   2017
 6          Taux de croissance du CA (%)    -19     592      78    825
 7               Taux de marge brute (%)    100     100     100    101
 8            Taux de marge d'EBITDA (%)    -92      49     -45     03
 9      Taux de marge opérationnelle (%)   -109       3     -57     03
 10                          Gestion BFR   2020    2019    2018   2017
 11                              BFR (€)  -106K  -57,4K    183K  24,1K
 12                 BFR exploitation (€)   226K    351K    370K   195K
 13            BFR hors exploitation (€)  -332K   -408K   -187K  -171K
 14                        BFR (j de CA)    -20     -88     446    104
 15           BFR exploitation (j de CA)    427     538     903    845
 16      BFR hors exploitation (j de CA)   -627    -626    -457   -741
 17        Délai de paiement clients (j)    606     868     110    113
 18   Délai de paiement fournisseurs (j)    559     908     674    794
 19            Ratio des stocks / CA (j)      0       0       0      0
 20                 Autonomie financière   2020    2019    2018   2017
 21       Capacité d'autofinancement (€)  -100K    194K     28K  76,9K
 22  Capacité d'autofinancement / CA (%)    -52      82      19     91
 23    Fonds de roulement net global (€)  1,46M   1,52M   1,38M  1,61M
 24                    Couverture du BFR   -138    -264      75    667
 25                       Trésorerie (€)  1,56M   1,57M   1,19M  1,58M
 26               Dettes financières (€)   228K    181K    201K   202K
 27            Capacité de remboursement    133     -72    -355    -18
 28        Ratio d'endettement (Gearing)    -09     -09     -07     -1
 29             Autonomie financière (%)     61     622     709    729
 30          Taux de levier (DFN/EBITDA)     75    -119     146   -560
 31                          Solvabilité   2020    2019    2018   2017
 32   Etat des dettes à 1 an au plus (€)   703K    805K    411K   333K
 33                   Liquidité générale     31      29      43     58
 34                Couverture des dettes    -02     -02     -03      0
 35                    Fonds propres (€)  1,45M   1,59M   1,44M  1,43M
 36                          Rentabilité   2020    2019    2018   2017
 37                      Marge nette (%)    -69      62      06     81
 38    Rentabilité sur fonds propres (%)    -92      93      06     48
 39           Rentabilité économique (%)    -56      58      04     35
 40                   Valeur ajoutée (€)  1,31M   1,52M   1,06M   545K
 41              Valeur ajoutée / CA (%)    679     637     706    648
 42                 Structure d'activité   2020    2019    2018   2017
 43     Salaires et charges sociales (€)  1,47M   1,37M    1,1M   528K
 44                    Salaires / CA (%)    764     575     737    628
 45                  Impôts et taxes (€)  28,5K   23,7K   19,9K  4,46K
 46    Chiffre d'affaires à l'export (€)    NaN     417     44K    15K,
                     0                                     1
 0         Téléphone :                        Non disponible
 1             Email :                        Non disponible
 2     Site internet :                        Non disponible
 3  Adresse complète :  25 RUE CLAUDE TILLIER 75012 PARIS 12,
    Prestataire                  Service      Unnamed: 2
 0          NaN   Financement innovation  En savoir plus
 1          NaN            Domiciliation  En savoir plus
 2          NaN                     Paie  En savoir plus
 3          NaN  Logiciel de facturation  En savoir plus
 4          NaN             Recouvrement  En savoir plus]

In [5]:
data_companies=dict()
for i in range(len(file_list)):
    a= pd.read_html('htmls/'+str(file_list[i]))
    data_companies[(file_list[i]).split('.html')[0]] = a

In [6]:
data_companies.keys()

dict_keys(['citility', 'poligma', 'voxcracy', 'LLL_2', 'bluenove', 'ecivis', 'make4', 'civimetric', 'voteetvous', 'vooter', 'organigram_97', 'forcity_mere', 'mymairie', 'quorum', 'fullmobs', 'mairesetcitoyens', 'parlonspo', 'make3', 'consultvox', 'loomio', 'politiker', 'citizenlabbv', 'datagora', 'ouiville', 'forcity', 'accromedias', 'lesbricodeurs', 'crowdpac', 'ledrenche', 'youvote', 'make2', 'ecreall_nova_ideo', 'neocity', 'citieszen', 'politicus', 'capcollectif', 'whip', 'voxestudio', 'democracyos', 'polipart', 'LLL', 'hacktiv', 'voxpublic', 'citybay_ambitions', 'politizr', 'digitalebox', 'mesopinions', 'assemblee_virtuelle', 'madeinvote', 'wesignit', 'mieuxvoter', 'kawaa', 'ciwik', 'data_for_good', 'digiworks', 'equivote_myopencity', 'make', 'kohero', 'openagora', 'moneparti', 'nousrassemble', 'bittle', 'marston_massiet', 'democratieouverte', 'koom', 'purpoz', 'reperage_urbain', 'regardscitoyens', 'D21', 'IDcity', 'Stig', 'opensourcepolitics', 'GOV', 'veritepol', 'fluicity', 'civocracy'])

In [7]:
type(data_companies['citility'])

list

In [8]:
type(data_companies['citility'][0])

pandas.core.frame.DataFrame

In [9]:
data_companies['citility'][0] # adress
# [0] provides basic information : adress, activity, number of employees, date of creation, directors 
# it's a dataframe

              0                                   1
0     Adresse :  5 RUE DE LA CLAIRE 69009 LYON 9EME
1    Activité :    Édition de logiciels applicatifs
2    Effectif :            0 salarié  (donnée 2019)
3    Création :                          05/05/2014
4  Dirigeants :   André MAY, ODICEO, Sabine SCHNECK

In [10]:
data_companies['citility'][1]
# [1] provides company information : SIREN, juridical form, TVA number, inscription RCA, n°, social capital 
# it's a dataframe

                      0                                           1
0               SIREN :                                 802 503 276
1       SIRET (siège) :                           802 503 276 00023
2     Forme juridique :         SAS, société par actions simplifiée
3        Numéro de TVA:                               FR07802503276
4  Inscription au RCS :  INSCRIT (au greffe de LYON, le 12/05/2014)
5          Numéro RCS :                     802 503 276 R.C.S. Lyon
6      Capital social :                                 39 620,00 €

In [11]:
pd.DataFrame(data_companies['citility'][2])
# [2] provides information on the activity - activité déclarée, code NAF, domaine d'activité, convention coll supposée, cloture exercice
# it's a dataframe

,0,1
0,Activité principale déclarée :,Edition de logiciels applicatifs.
1,Code NAF ou APE :,58.29C (Édition de logiciels applicatifs)
2,Domaine d’activité :,Édition
3,Convention collective supposéeNous avons esti...,Bureaux d'études techniques et sociétés de con...
4,Date de clôture d'exercice comptable :,31/12/2023

In [12]:
pd.DataFrame(data_companies['citility'][3])
# provides data per year for financial performance
# it's a dataframe with 3 columns

                            Performance   2017    2016
0                Chiffre d'affaires (€)    NaN   30,7K
1                       Marge brute (€)    NaN    527K
2                      EBITDA - EBE (€)    NaN   -295K
3           Résultat d'exploitation (€)    NaN   -296K
4                      Résultat net (€)  -562K   -238K
5                            Croissance   2017    2016
6          Taux de croissance du CA (%)    NaN       4
7               Taux de marge brute (%)    NaN   1,72K
8            Taux de marge d'EBITDA (%)    NaN    -961
9      Taux de marge opérationnelle (%)    NaN    -965
10                          Gestion BFR   2017    2016
11                              BFR (€)  -247K   -213K
12                 BFR exploitation (€)  -134K   -217K
13            BFR hors exploitation (€)  -112K   3,78K
14                        BFR (j de CA)    NaN  -2,53K
15           BFR exploitation (j de CA)    NaN  -2,58K
16      BFR hors exploitation (j de CA)    NaN     449
17        Délai de paiement clients (j)    NaN     535
18   Délai de paiement fournisseurs (j)    NaN     566
19            Ratio des stocks / CA (j)    NaN       0
20                 Autonomie financière   2017    2016
21       Capacité d'autofinancement (€)    NaN   -289K
22  Capacité d'autofinancement / CA (%)    NaN    -942
23    Fonds de roulement net global (€)   549K   -210K
24                    Couverture du BFR    -22       1
25                       Trésorerie (€)   796K    2,9K
26               Dettes financières (€)   406K    476K
27            Capacité de remboursement    NaN     -16
28        Ratio d'endettement (Gearing)    -03      12
29             Autonomie financière (%)    617     278
30          Taux de levier (DFN/EBITDA)    NaN     -16
31                          Solvabilité   2017    2016
32   Etat des dettes à 1 an au plus (€)   591K    604K
33                   Liquidité générale     17      05
34                Couverture des dettes    -32      23
35                    Fonds propres (€)  1,38M    382K
36                          Rentabilité   2017    2016
37                      Marge nette (%)    NaN    -775
38    Rentabilité sur fonds propres (%)    NaN    -623
39           Rentabilité économique (%)    NaN    -173
40                   Valeur ajoutée (€)    NaN    351K
41              Valeur ajoutée / CA (%)    NaN   1,14K
42                 Structure d'activité   2017    2016
43     Salaires et charges sociales (€)    NaN    636K
44                    Salaires / CA (%)    NaN   2,07K
45                  Impôts et taxes (€)    NaN   9,16K

In [13]:
pd.DataFrame(data_companies['citility'][4])
# it's a dataframe

                    0                                   1
0         Téléphone :                      Non disponible
1             Email :                      Non disponible
2     Site internet :                      Non disponible
3  Adresse complète :  5 RUE DE LA CLAIRE 69009 LYON 9EME

## from nested dataframes in dictionary to a dataframe

In [14]:
citility=pd.concat([pd.DataFrame(data_companies['citility'][0]), pd.DataFrame(data_companies['citility'][1]), pd.DataFrame(data_companies['citility'][2][0:3]), pd.DataFrame(data_companies['citility'][4])], axis=0).reset_index(drop=True)

In [15]:
citility

                                 0                                           1
0                        Adresse :          5 RUE DE LA CLAIRE 69009 LYON 9EME
1                       Activité :            Édition de logiciels applicatifs
2                       Effectif :                    0 salarié  (donnée 2019)
3                       Création :                                  05/05/2014
4                     Dirigeants :           André MAY, ODICEO, Sabine SCHNECK
5                          SIREN :                                 802 503 276
6                  SIRET (siège) :                           802 503 276 00023
7                Forme juridique :         SAS, société par actions simplifiée
8                   Numéro de TVA:                               FR07802503276
9             Inscription au RCS :  INSCRIT (au greffe de LYON, le 12/05/2014)
10                    Numéro RCS :                     802 503 276 R.C.S. Lyon
11                Capital social :                                 39 620,00 €
12  Activité principale déclarée :           Edition de logiciels applicatifs.
13               Code NAF ou APE :   58.29C (Édition de logiciels applicatifs)
14            Domaine d’activité :                                     Édition
15                     Téléphone :                              Non disponible
16                         Email :                              Non disponible
17                 Site internet :                              Non disponible
18              Adresse complète :          5 RUE DE LA CLAIRE 69009 LYON 9EME

In [16]:
list(data_companies.keys())

['citility',
 'poligma',
 'voxcracy',
 'LLL_2',
 'bluenove',
 'ecivis',
 'make4',
 'civimetric',
 'voteetvous',
 'vooter',
 'organigram_97',
 'forcity_mere',
 'mymairie',
 'quorum',
 'fullmobs',
 'mairesetcitoyens',
 'parlonspo',
 'make3',
 'consultvox',
 'loomio',
 'politiker',
 'citizenlabbv',
 'datagora',
 'ouiville',
 'forcity',
 'accromedias',
 'lesbricodeurs',
 'crowdpac',
 'ledrenche',
 'youvote',
 'make2',
 'ecreall_nova_ideo',
 'neocity',
 'citieszen',
 'politicus',
 'capcollectif',
 'whip',
 'voxestudio',
 'democracyos',
 'polipart',
 'LLL',
 'hacktiv',
 'voxpublic',
 'citybay_ambitions',
 'politizr',
 'digitalebox',
 'mesopinions',
 'assemblee_virtuelle',
 'madeinvote',
 'wesignit',
 'mieuxvoter',
 'kawaa',
 'ciwik',
 'data_for_good',
 'digiworks',
 'equivote_myopencity',
 'make',
 'kohero',
 'openagora',
 'moneparti',
 'nousrassemble',
 'bittle',
 'marston_massiet',
 'democratieouverte',
 'koom',
 'purpoz',
 'reperage_urbain',
 'regardscitoyens',
 'D21',
 'IDcity',
 'Stig',
 'opensourcepolitics',
 'GOV',
 'veritepol',
 'fluicity',
 'civocracy']

In [17]:
pd.DataFrame(data_companies['citility'][2][0:3])

                                0                                          1
0  Activité principale déclarée :          Edition de logiciels applicatifs.
1               Code NAF ou APE :  58.29C (Édition de logiciels applicatifs)
2            Domaine d’activité :                                    Édition

In [70]:
new_df=pd.concat([pd.DataFrame(data_companies['citility'][0][0]), pd.DataFrame(data_companies['citility'][1][0]), pd.DataFrame(data_companies['citility'][2][0][0:3])], axis=0).reset_index(drop=True)
new_df.columns=['ind']
for i in list(data_companies.keys()):
    a= pd.concat([pd.DataFrame(data_companies[str(i)][0]), pd.DataFrame(data_companies[str(i)][1]), pd.DataFrame(data_companies[str(i)][2][0:3])], axis=0).reset_index(drop=True)   
    a.columns=['ind', i]
    new_df= new_df.merge(a, how='outer')

In [72]:
new_df.set_index("ind", inplace=True)

In [74]:
new_df.drop(['SIREN :', 'SIRET (siège) :', 'Numéro de TVA:', 'Numéro RCS :', 'Capital variable (minimum) :'], axis=0, inplace=True)

In [76]:
new_df= new_df.T

In [78]:
new_df.reset_index(inplace=True)

In [84]:
col= [i for i in new_df.columns if "onvention" in i]
new_df.drop(columns=col, inplace=True)

In [87]:
new_df.rename(columns={'index':'companyName'}, inplace=True)

In [91]:
new_df.reset_index(inplace=True)

In [93]:
new_df.rename(columns={'index':'company_id'}, inplace=True)

In [94]:
new_df.head()

ind,company_id,companyName,Adresse :,Activité :,Effectif :,Création :,Dirigeants :,Forme juridique :,Inscription au RCS :,Capital social :,Activité principale déclarée :,Code NAF ou APE :,Domaine d’activité :,Dirigeant :,Inscription au RNA :,Identifiant association :,Objet de l'association :,Statut INSEE :
0,0,citility,5 RUE DE LA CLAIRE 69009 LYON 9EME,Édition de logiciels applicatifs,0 salarié (donnée 2019),05/05/2014,"André MAY, ODICEO, Sabine SCHNECK","SAS, société par actions simplifiée","INSCRIT (au greffe de LYON, le 12/05/2014)","39 620,00 €",Edition de logiciels applicatifs.,58.29C (Édition de logiciels applicatifs),Édition,NaN,NaN,NaN,NaN,NaN
1,1,poligma,RPT BENJAMIN FRANKLIN 34960 MONTPELLIER CEDEX 2,Conseil en systèmes et logiciels informatiques,Entre 3 et 5 salariés (donnée 2020),01/09/2015,NaN,"SAS, société par actions simplifiée","INSCRIT (au greffe de MONTPELLIER, le 11/09/2015)","20 944,00 €",Développement de services informatiques et num...,62.02A (Conseil en systèmes et logiciels infor...,"Programmation, conseil et autres activités inf...",Philippe GERARD,NaN,NaN,NaN,NaN
2,2,voxcracy,1133 RTE FENERIE 06580 PEGOMAS,Programmation informatique,0 salarié,01/09/2014,"Olivier ROCCA, Pascal RUSCICA","SAS, société par actions simplifiée","INSCRIT (au greffe de GRASSE, le 17/07/2014)","1 000,00 €","La recherche, le développement et la commercia...",62.01Z (Programmation informatique),"Programmation, conseil et autres activités inf...",NaN,NaN,NaN,NaN,NaN
3,3,LLL_2,16 RUE DU CAIRE 75002 PARIS 2,Autres activités de soutien aux entreprises n....,Entre 3 et 5 salariés (donnée 2020),16/01/2015,"ANNAMAMASHOW, Raymond Maeder, 3APEXCO","SAS, société par actions simplifiée","INSCRIT (au greffe de PARIS, le 03/02/2015)","45 000,00 €",Développement de nouvelles formes de collabora...,82.99Z (Autres activités de soutien aux entrep...,Activités administratives et autres activités ...,NaN,NaN,NaN,NaN,NaN
4,4,bluenove,112 B RUE CARDINET 75017 PARIS 17,Conseil pour les affaires et autres conseils d...,Entre 20 et 49 salariés (donnée 2020),23/01/2008,"GROUPE BLUENOVE INC., Guillaume Drancy, Carole...","SAS, société par actions simplifiée","INSCRIT (au greffe de PARIS, le 21/11/2019)","56 445,00 €",L'activité de conseil en stratégie d'accompagn...,70.22Z (Conseil pour les affaires et autres co...,Activités des sièges sociaux ; conseil de gestion,NaN,NaN,NaN,NaN,NaN

In [95]:
new_df.to_csv('companies_info_data.csv', sep=';', index=False)

## Financial info

In [31]:
finance_df=pd.DataFrame(data_companies['citility'][3])
for i in list(data_companies.keys()):
    if len(data_companies[str(i)][3]) > 10:
        b= pd.DataFrame(data_companies[str(i)][3]).set_index("Performance").add_suffix('_'+i)
        finance_df=finance_df.merge(b, how='outer', on="Performance")
finance_df.drop(columns=['2017', '2016'], inplace=True)

In [96]:
finance_df.head()

,Performance,2017_citility,2016_citility,2019_voxcracy,2018_voxcracy,2017_voxcracy,2016_voxcracy,2020_LLL_2,2019_LLL_2,2018_LLL_2,...,2020_reperage_urbain,2019_reperage_urbain,2018_reperage_urbain,2016_IDcity,2019_Stig,2018_Stig,2021_opensourcepolitics,2020_opensourcepolitics,2019_opensourcepolitics,2018_opensourcepolitics
0,Chiffre d'affaires (€),NaN,"30,7K","46,3K","16,7K","1,74K",0,473K,462K,300K,...,113K,214K,232K,"9,95K",151K,134,"1,33M",824K,433K,259K
1,Marge brute (€),NaN,527K,"46,3K",157K,"75,9K",NaN,473K,462K,300K,...,113K,214K,232K,"9,95K",151K,135,"1,34M",686K,433K,259K
2,EBITDA - EBE (€),NaN,-295K,"-31,5K",-123K,"-24,4K","-1,08K","24,7K",160K,"89,7K",...,"-24,1K","-23,3K","19,3K",-496,"55,2K","-9,86K",277K,205K,"65,9K","17,2K"
3,Résultat d'exploitation (€),NaN,-296K,"-38,5K",-130K,"-30,3K","-4,91K","-42,7K","95,2K","25,9K",...,"-24,5K","-23,7K",19K,-495,"54,2K","-11,5K",284K,188K,"64,2K","15,4K"
4,Résultat net (€),-562K,-238K,-39K,-112K,"-23,4K","-4,91K","-44,9K","62,4K","19,8K",...,"-24,9K","-24,4K","16,9K",-495,"38,8K","-2,04K",235K,154K,"60,2K","14,3K"

In [33]:
finance_df2= (finance_df.set_index("Performance").T)

In [34]:
finance_df2.reset_index(inplace=True)

In [35]:
finance_df2.columns

Index(['index', 'Chiffre d'affaires (€)', 'Marge brute (€)',
       'EBITDA - EBE (€)', 'Résultat d'exploitation (€)', 'Résultat net (€)',
       'Croissance', 'Taux de croissance du CA (%)', 'Taux de marge brute (%)',
       'Taux de marge d'EBITDA (%)', 'Taux de marge opérationnelle (%)',
       'Gestion BFR', 'BFR (€)', 'BFR exploitation (€)',
       'BFR hors exploitation (€)', 'BFR (j de CA)',
       'BFR exploitation (j de CA)', 'BFR hors exploitation (j de CA)',
       'Délai de paiement clients (j)', 'Délai de paiement fournisseurs (j)',
       'Ratio des stocks / CA (j)', 'Autonomie financière',
       'Capacité d'autofinancement (€)', 'Capacité d'autofinancement / CA (%)',
       'Fonds de roulement net global (€)', 'Couverture du BFR',
       'Trésorerie (€)', 'Dettes financières (€)', 'Capacité de remboursement',
       'Ratio d'endettement (Gearing)', 'Autonomie financière (%)',
       'Taux de levier (DFN/EBITDA)', 'Solvabilité',
       'Etat des dettes à 1 an au plus (€)', 'Liquidité générale',
       'Couverture des dettes', 'Fonds propres (€)', 'Rentabilité',
       'Marge nette (%)', 'Rentabilité sur fonds propres (%)',
       'Rentabilité économique (%)', 'Valeur ajoutée (€)',
       'Valeur ajoutée / CA (%)', 'Structure d'activité',
       'Salaires et charges sociales (€)', 'Salaires / CA (%)',
       'Impôts et taxes (€)', 'Chiffre d'affaires à l'export (€)'],
      dtype='object', name='Performance')

In [36]:
import inflection
import re
new_col_names=[]
for i in list(finance_df2.columns):
    i=i.lower().replace(' de', '_').replace(' du', '_').replace("'", '').replace(' ', '_').replace('é', 'e').replace('(€)','e').replace('(%)','pc').replace('/','sur').replace('à', 'a').replace('è', 'e').replace('(', '').replace(')', '').replace('ô', 'o').replace('__', '_').replace('s_t', 'surdet')
    new_col_names.append(inflection.underscore(i))
print(new_col_names)

['index', 'chiffre_daffaires_e', 'marge_brute_e', 'ebitda___ebe_e', 'resultat_dexploitation_e', 'resultat_net_e', 'croissance', 'taux_croissance_ca_pc', 'taux_marge_brute_pc', 'taux_marge_debitda_pc', 'taux_marge_operationnelle_pc', 'gestion_bfr', 'bfr_e', 'bfr_exploitation_e', 'bfr_hors_exploitation_e', 'bfr_j_ca', 'bfr_exploitation_j_ca', 'bfr_hors_exploitation_j_ca', 'delai_paiement_clients_j', 'delai_paiement_fournisseurs_j', 'ratio_s_stocks_sur_ca_j', 'autonomie_financiere', 'capacite_dautofinancement_e', 'capacite_dautofinancement_sur_ca_pc', 'fonds_roulement_net_global_e', 'couverture_bfr', 'tresorerie_e', 'dettes_financieres_e', 'capacite_remboursement', 'ratio_dendettement_gearing', 'autonomie_financiere_pc', 'taux_levier_dfnsurebitda', 'solvabilite', 'etat_surdettes_a_1_an_au_plus_e', 'liquidite_generale', 'couverture_surdettes', 'fonds_propres_e', 'rentabilite', 'marge_nette_pc', 'rentabilite_sur_fonds_propres_pc', 'rentabilite_economique_pc', 'valeur_ajoutee_e', 'valeur_ajoutee_sur_ca_pc', 'structure_dactivite', 'salaires_et_charges_sociales_e', 'salaires_sur_ca_pc', 'impots_et_taxes_e', 'chiffre_daffaires_a_lexport_e']

In [37]:
finance_df2.columns= new_col_names

In [38]:
finance_df2.head()

,index,chiffre_daffaires_e,marge_brute_e,ebitda___ebe_e,resultat_dexploitation_e,resultat_net_e,croissance,taux_croissance_ca_pc,taux_marge_brute_pc,taux_marge_debitda_pc,...,marge_nette_pc,rentabilite_sur_fonds_propres_pc,rentabilite_economique_pc,valeur_ajoutee_e,valeur_ajoutee_sur_ca_pc,structure_dactivite,salaires_et_charges_sociales_e,salaires_sur_ca_pc,impots_et_taxes_e,chiffre_daffaires_a_lexport_e
0,2017_citility,NaN,NaN,NaN,NaN,-562K,2017,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2017,NaN,NaN,NaN,NaN
1,2016_citility,"30,7K",527K,-295K,-296K,-238K,2016,4,"1,72K",-961,...,-775,-623,-173,351K,"1,14K",2016,636K,"2,07K","9,16K",NaN
2,2019_voxcracy,"46,3K","46,3K","-31,5K","-38,5K",-39K,2019,177,100,-682,...,-842,-76,-63,"2,17K",47,2019,"33,6K",725,137,NaN
3,2018_voxcracy,"16,7K",157K,-123K,-130K,-112K,2018,861,940,-734,...,-668,-202,-169,-21K,-126,2018,101K,602,"1,12K",5K
4,2017_voxcracy,"1,74K","75,9K","-24,4K","-30,3K","-23,4K",2017,NaN,"4,36K","-1,4K",...,"-1,35K",-41,-39,"-5,04K",-290,2017,"19,1K","1,1K",329,NaN

In [39]:
import re

def fix_columns(x):
    x=str(x)
    if x== 'nan':
        return 0
    elif 'K' in x:
        if ',' in x:
            return int(re.split('[,K]', x)[0]+re.split('[,K]', x)[1]+'0'*(3-len(re.split('[,K]', x)[1])))
        else:
            return int(x.replace('K', '000'))
    elif 'M' in x:
        if ',' in x:
            return int(re.split('[,M]', x)[0]+re.split('[,M]', x)[1]+'0'*(6-len(re.split('[,M]', x)[1])))
        else:
            return int(x.replace('M', '000'))
    else:
        return x

In [40]:
# to test the function on one series 
# finance_df2['chiffre_daffaires_e'].apply(fix_columns)

In [53]:
finance_df2.set_index("index", inplace=True)

In [42]:
for i in list(finance_df2.columns)[0:]: 
    finance_df2[i]= finance_df2[i].apply(fix_columns)

In [43]:
#### NEW COLUMN NAME 
# finance_df2=finance_df2.apply(pd.to_numeric).reset_index()

In [44]:
finance_df2.dtypes

chiffre_daffaires_e                    object
marge_brute_e                          object
ebitda___ebe_e                         object
resultat_dexploitation_e               object
resultat_net_e                         object
croissance                             object
taux_croissance_ca_pc                  object
taux_marge_brute_pc                    object
taux_marge_debitda_pc                  object
taux_marge_operationnelle_pc           object
gestion_bfr                            object
bfr_e                                  object
bfr_exploitation_e                     object
bfr_hors_exploitation_e                object
bfr_j_ca                               object
bfr_exploitation_j_ca                  object
bfr_hors_exploitation_j_ca             object
delai_paiement_clients_j               object
delai_paiement_fournisseurs_j          object
ratio_s_stocks_sur_ca_j                object
autonomie_financiere                   object
capacite_dautofinancement_e            object
capacite_dautofinancement_sur_ca_pc    object
fonds_roulement_net_global_e           object
couverture_bfr                         object
tresorerie_e                           object
dettes_financieres_e                   object
capacite_remboursement                 object
ratio_dendettement_gearing             object
autonomie_financiere_pc                object
taux_levier_dfnsurebitda               object
solvabilite                            object
etat_surdettes_a_1_an_au_plus_e        object
liquidite_generale                     object
couverture_surdettes                   object
fonds_propres_e                        object
rentabilite                            object
marge_nette_pc                         object
rentabilite_sur_fonds_propres_pc       object
rentabilite_economique_pc              object
valeur_ajoutee_e                       object
valeur_ajoutee_sur_ca_pc               object
structure_dactivite                    object
salaires_et_charges_sociales_e         object
salaires_sur_ca_pc                     object
impots_et_taxes_e                      object
chiffre_daffaires_a_lexport_e          object
dtype: object

In [45]:
finance_df2.head(10)

,chiffre_daffaires_e,marge_brute_e,ebitda___ebe_e,resultat_dexploitation_e,resultat_net_e,croissance,taux_croissance_ca_pc,taux_marge_brute_pc,taux_marge_debitda_pc,taux_marge_operationnelle_pc,...,marge_nette_pc,rentabilite_sur_fonds_propres_pc,rentabilite_economique_pc,valeur_ajoutee_e,valeur_ajoutee_sur_ca_pc,structure_dactivite,salaires_et_charges_sociales_e,salaires_sur_ca_pc,impots_et_taxes_e,chiffre_daffaires_a_lexport_e
index,,,,,,,,,,,,,,,,,,,,,
2017_citility,0,0,0,0,-562000,2017,0,0,0,0,...,0,0,0,0,0,2017,0,0,0,0
2016_citility,30700,527000,-295000,-296000,-238000,2016,4,1720,-961,-965,...,-775,-623,-173,351000,1140,2016,636000,2070,9160,0
2019_voxcracy,46300,46300,-31500,-38500,-39000,2019,177,100,-682,-833,...,-842,-76,-63,2170,47,2019,33600,725,137,0
2018_voxcracy,16700,157000,-123000,-130000,-112000,2018,861,940,-734,-776,...,-668,-202,-169,-21000,-126,2018,101000,602,1120,5000
2017_voxcracy,1740,75900,-24400,-30300,-23400,2017,0,4360,-1400,-1740,...,-1350,-41,-39,-5040,-290,2017,19100,1100,329,0
2016_voxcracy,0,0,-1080,-4910,-4910,2016,0,0,0,0,...,0,-4420,-177,-942,0,2016,0,0,140,0
2020_LLL_2,473000,473000,24700,-42700,-44900,2020,25,100,52,-9,...,-95,-437,-37,136000,287,2020,97100,205,14200,0
2019_LLL_2,462000,462000,160000,95200,62400,2019,539,100,346,206,...,135,423,86,292000,632,2019,126000,274,7350,0
2018_LLL_2,300000,300000,89700,25900,19800,2018,0,100,299,86,...,66,232,38,175000,584,2018,80200,267,5220,0
2017_LLL_2,0.0,0,0,0,0,2017.0,0,0,0,0,...,0,0,0,0,0,2017.0,0,0,0,0

In [46]:
#finance_df2["company"]= 
#[re.split('_', str(finance_df2["index"]))][0]
def create_company_col(x):
    x=str(x)
    return x.split('_')[1]

In [56]:
finance_df2.reset_index(inplace=True)

In [ ]:
finance_df2["company"]= finance_df2["index"].apply(create_company_col)

In [58]:
finance_df2.head()

,index,chiffre_daffaires_e,marge_brute_e,ebitda___ebe_e,resultat_dexploitation_e,resultat_net_e,croissance,taux_croissance_ca_pc,taux_marge_brute_pc,taux_marge_debitda_pc,...,rentabilite_sur_fonds_propres_pc,rentabilite_economique_pc,valeur_ajoutee_e,valeur_ajoutee_sur_ca_pc,structure_dactivite,salaires_et_charges_sociales_e,salaires_sur_ca_pc,impots_et_taxes_e,chiffre_daffaires_a_lexport_e,company
0,citility,0,0,0,0,-562000,2017,0,0,0,...,0,0,0,0,2017,0,0,0,0,citility
1,citility,30700,527000,-295000,-296000,-238000,2016,4,1720,-961,...,-623,-173,351000,1140,2016,636000,2070,9160,0,citility
2,voxcracy,46300,46300,-31500,-38500,-39000,2019,177,100,-682,...,-76,-63,2170,47,2019,33600,725,137,0,voxcracy
3,voxcracy,16700,157000,-123000,-130000,-112000,2018,861,940,-734,...,-202,-169,-21000,-126,2018,101000,602,1120,5000,voxcracy
4,voxcracy,1740,75900,-24400,-30300,-23400,2017,0,4360,-1400,...,-41,-39,-5040,-290,2017,19100,1100,329,0,voxcracy

In [61]:
finance_df2.rename(columns={'croissance':'annee'}, inplace=True)

In [62]:
finance_df2.isna().sum()

index                                  0
chiffre_daffaires_e                    0
marge_brute_e                          0
ebitda___ebe_e                         0
resultat_dexploitation_e               0
resultat_net_e                         0
annee                                  0
taux_croissance_ca_pc                  0
taux_marge_brute_pc                    0
taux_marge_debitda_pc                  0
taux_marge_operationnelle_pc           0
gestion_bfr                            0
bfr_e                                  0
bfr_exploitation_e                     0
bfr_hors_exploitation_e                0
bfr_j_ca                               0
bfr_exploitation_j_ca                  0
bfr_hors_exploitation_j_ca             0
delai_paiement_clients_j               0
delai_paiement_fournisseurs_j          0
ratio_s_stocks_sur_ca_j                0
autonomie_financiere                   0
capacite_dautofinancement_e            0
capacite_dautofinancement_sur_ca_pc    0
fonds_roulement_net_global_e           0
couverture_bfr                         0
tresorerie_e                           0
dettes_financieres_e                   0
capacite_remboursement                 0
ratio_dendettement_gearing             0
autonomie_financiere_pc                0
taux_levier_dfnsurebitda               0
solvabilite                            0
etat_surdettes_a_1_an_au_plus_e        0
liquidite_generale                     0
couverture_surdettes                   0
fonds_propres_e                        0
rentabilite                            0
marge_nette_pc                         0
rentabilite_sur_fonds_propres_pc       0
rentabilite_economique_pc              0
valeur_ajoutee_e                       0
valeur_ajoutee_sur_ca_pc               0
structure_dactivite                    0
salaires_et_charges_sociales_e         0
salaires_sur_ca_pc                     0
impots_et_taxes_e                      0
chiffre_daffaires_a_lexport_e          0
company                                0
dtype: int64

In [64]:
finance_df2=finance_df2[['company', 'annee', 'chiffre_daffaires_e', 'marge_brute_e', 'resultat_dexploitation_e', 'resultat_net_e', 'taux_croissance_ca_pc', 'taux_marge_brute_pc', 'taux_marge_operationnelle_pc', 'gestion_bfr', 'bfr_e', 'bfr_exploitation_e', 'bfr_hors_exploitation_e', 'bfr_j_ca', 'bfr_exploitation_j_ca', 'bfr_hors_exploitation_j_ca', 'delai_paiement_clients_j', 'delai_paiement_fournisseurs_j', 'ratio_s_stocks_sur_ca_j', 'autonomie_financiere', 'capacite_dautofinancement_e', 'capacite_dautofinancement_sur_ca_pc', 'fonds_roulement_net_global_e', 'couverture_bfr', 'tresorerie_e', 'dettes_financieres_e', 'capacite_remboursement', 'ratio_dendettement_gearing', 'autonomie_financiere_pc', 'taux_levier_dfnsurebitda', 'solvabilite', 'etat_surdettes_a_1_an_au_plus_e', 'liquidite_generale', 'couverture_surdettes', 'fonds_propres_e', 'rentabilite', 'marge_nette_pc', 'rentabilite_sur_fonds_propres_pc', 'rentabilite_economique_pc', 'valeur_ajoutee_e', 'valeur_ajoutee_sur_ca_pc', 'structure_dactivite', 'salaires_et_charges_sociales_e', 'salaires_sur_ca_pc', 'impots_et_taxes_e', 'chiffre_daffaires_a_lexport_e']]

In [66]:
finance_df2.reset_index()

,index,company,annee,chiffre_daffaires_e,marge_brute_e,resultat_dexploitation_e,resultat_net_e,taux_croissance_ca_pc,taux_marge_brute_pc,taux_marge_operationnelle_pc,...,marge_nette_pc,rentabilite_sur_fonds_propres_pc,rentabilite_economique_pc,valeur_ajoutee_e,valeur_ajoutee_sur_ca_pc,structure_dactivite,salaires_et_charges_sociales_e,salaires_sur_ca_pc,impots_et_taxes_e,chiffre_daffaires_a_lexport_e
0,0,citility,2017,0,0,0,-562000,0,0,0,...,0,0,0,0,0,2017,0,0,0,0
1,1,citility,2016,30700,527000,-296000,-238000,4,1720,-965,...,-775,-623,-173,351000,1140,2016,636000,2070,9160,0
2,2,voxcracy,2019,46300,46300,-38500,-39000,177,100,-833,...,-842,-76,-63,2170,47,2019,33600,725,137,0
3,3,voxcracy,2018,16700,157000,-130000,-112000,861,940,-776,...,-668,-202,-169,-21000,-126,2018,101000,602,1120,5000
4,4,voxcracy,2017,1740,75900,-30300,-23400,0,4360,-1740,...,-1350,-41,-39,-5040,-290,2017,19100,1100,329,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,69,Stig,2018,134,135,-11500,-2040,0,101,-8610,...,-1520,-915,-892,-9860,-7360,2018,0,0,0,0
70,70,opensourcepolitics,2021,1330000,1340000,284000,235000,614,101,213,...,177,494,314,1030000,771,2021,793000,596,7030,160000
71,71,opensourcepolitics,2020,824000,686000,188000,154000,905,832,228,...,186,569,305,658000,798,2020,462000,561,4050,123000
72,72,opensourcepolitics,2019,433000,433000,64200,60200,67,100,148,...,139,517,222,326000,754,2019,279000,644,1620,0
73,73,opensourcepolitics,2018,259000,259000,15400,14300,442,100,59,...,55,254,144,135000,523,2018,125000,484,1160,0

In [67]:
finance_df2.rename(columns={'index':'id_company_peryear'}, inplace=True)

In [97]:
finance_df2.head()

,company,annee,chiffre_daffaires_e,marge_brute_e,resultat_dexploitation_e,resultat_net_e,taux_croissance_ca_pc,taux_marge_brute_pc,taux_marge_operationnelle_pc,gestion_bfr,...,marge_nette_pc,rentabilite_sur_fonds_propres_pc,rentabilite_economique_pc,valeur_ajoutee_e,valeur_ajoutee_sur_ca_pc,structure_dactivite,salaires_et_charges_sociales_e,salaires_sur_ca_pc,impots_et_taxes_e,chiffre_daffaires_a_lexport_e
0,citility,2017,0,0,0,-562000,0,0,0,2017,...,0,0,0,0,0,2017,0,0,0,0
1,citility,2016,30700,527000,-296000,-238000,4,1720,-965,2016,...,-775,-623,-173,351000,1140,2016,636000,2070,9160,0
2,voxcracy,2019,46300,46300,-38500,-39000,177,100,-833,2019,...,-842,-76,-63,2170,47,2019,33600,725,137,0
3,voxcracy,2018,16700,157000,-130000,-112000,861,940,-776,2018,...,-668,-202,-169,-21000,-126,2018,101000,602,1120,5000
4,voxcracy,2017,1740,75900,-30300,-23400,0,4360,-1740,2017,...,-1350,-41,-39,-5040,-290,2017,19100,1100,329,0

In [68]:
finance_df2.to_csv("companies_finance_data.csv", sep=';', index=False)