## Importing information

In [1]:
import pandas as pd
import json
import numpy as np
import os

In [2]:
def create_profile(x, url):
    with open(str(url)+str(x)) as f:
        dict1 = json.load(f)
    list_col= ['experience', 'education', 'languages','languages','publications', 'certifications','volunteer', 'honors', 'projects']
    for n in list_col:
        if n in dict1:
            for i in range(len(dict1[n])): 
                dict1[str(n+str(i+1))]= dict1[n][i]
    data = pd.DataFrame.from_dict(dict1, orient='index').T
    return data

In [3]:
file_list = [f for f in os.listdir('../data/jsons') if f.endswith(".json")]
len(file_list)

49

In [4]:
initial_profile=create_profile('brachetantoine.json', '../data/jsons/')

In [5]:
profiles = initial_profile
for i in file_list:
    a= create_profile(i, '../data/jsons/')
    profiles= pd.concat((profiles,a),axis=0)

In [6]:
file_list2 = [f for f in os.listdir('../data/jsons2') if f.endswith(".json")]
len(file_list2)

124

In [7]:
profiles2 = initial_profile
for i in file_list2:
    a= create_profile(i,'../data/jsons2/')
    profiles2= pd.concat((profiles2,a),axis=0)

In [8]:
data=pd.concat([profiles, profiles2]).reset_index(drop=True)
data.head(2)

,summary,industryName,lastName,student,geoCountryName,geoCountryUrn,geoLocationBackfilled,elt,industryUrn,firstName,...,publications9,publications10,maidenName,projects8,certifications5,certifications6,certifications7,certifications8,certifications9,certifications10
0,Antoine croit à l’intelligence de tous et à la...,IT Services and IT Consulting,Brachet,False,France,urn:li:fs_geo:105015875,False,False,urn:li:fs_industry:96,Antoine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,French Entrepreneur - Founder and Managing Par...,Venture Capital and Private Equity Principals,Demri,False,France,urn:li:fs_geo:105015875,False,False,urn:li:fs_industry:106,Bobby,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Initial dataset cleaning

In [9]:
data.shape

(173, 89)

In [10]:
print(list(data.columns))

['summary', 'industryName', 'lastName', 'student', 'geoCountryName', 'geoCountryUrn', 'geoLocationBackfilled', 'elt', 'industryUrn', 'firstName', 'entityUrn', 'geoLocation', 'geoLocationName', 'location', 'headline', 'displayPictureUrl', 'img_100_100', 'img_200_200', 'img_400_400', 'img_800_800', 'profile_id', 'profile_urn', 'member_urn', 'public_id', 'experience', 'education', 'languages', 'publications', 'certifications', 'volunteer', 'honors', 'projects', 'experience1', 'experience2', 'experience3', 'experience4', 'experience5', 'education1', 'education2', 'education3', 'languages1', 'languages2', 'languages3', 'publications1', 'publications2', 'publications3', 'publications4', 'publications5', 'publications6', 'publications7', 'publications8', 'locationName', 'honors1', 'honors2', 'honors3', 'honors4', 'honors5', 'honors6', 'honors7', 'volunteer1', 'volunteer2', 'volunteer3', 'projects1', 'projects2', 'projects3', 'birthDate', 'languages4', 'projects4', 'projects5', 'address', 'languages5', 'languages6', 'certifications1', 'projects6', 'projects7', 'certifications2', 'certifications3', 'certifications4', 'languages7', 'publications9', 'publications10', 'maidenName', 'projects8', 'certifications5', 'certifications6', 'certifications7', 'certifications8', 'certifications9', 'certifications10']

### Drop duplicates in rows

In [11]:
mask = data.duplicated(subset=['headline'], keep='last')
dropped = data.loc[mask]
dropped

,summary,industryName,lastName,student,geoCountryName,geoCountryUrn,geoLocationBackfilled,elt,industryUrn,firstName,...,publications9,publications10,maidenName,projects8,certifications5,certifications6,certifications7,certifications8,certifications9,certifications10
0,Antoine croit à l’intelligence de tous et à la...,IT Services and IT Consulting,Brachet,False,France,urn:li:fs_geo:105015875,False,False,urn:li:fs_industry:96,Antoine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,French Entrepreneur - Founder and Managing Par...,Venture Capital and Private Equity Principals,Demri,False,France,urn:li:fs_geo:105015875,False,False,urn:li:fs_industry:106,Bobby,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Inspired by the power we can build to change t...,Civic and Social Organizations,Durieux,False,France,urn:li:fs_geo:105015875,False,False,urn:li:fs_industry:90,Sarah,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Antoine croit à l’intelligence de tous et à la...,IT Services and IT Consulting,Brachet,False,France,urn:li:fs_geo:105015875,False,False,urn:li:fs_industry:96,Antoine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,⇒ Rendez-vous sur jerem.io pour télécharger mo...,"Technology, Information and Internet",Paret,False,France,urn:li:fs_geo:105015875,False,False,urn:li:fs_industry:6,Jeremie,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data.drop_duplicates(subset=['headline'], keep='last', inplace=True)

### Dropping unnecessary columns (specific to LIn, personal information, etc.)

In [13]:
pd.options.display.max_rows = 100

In [14]:
todrop=['industryName', 'experience', 'education', 'languages','languages','publications', 
        'certifications','volunteer', 'honors', 'projects', 
        'displayPictureUrl', 'img_100_100', 'img_200_200', 'img_400_400', 
        'img_800_800', 'student', 'lastName', 'firstName', 'maidenName', 'birthDate', 
        'address','geoCountryUrn', 'geoLocationBackfilled', 'elt', 'industryUrn',
        'entityUrn', 'geoLocation', 'location', 'locationName', 
        'profile_id', 'profile_urn', 'member_urn', 'public_id']
data.drop(columns=todrop, inplace=True)

In [15]:
data.describe().T.sort_index()

,count,unique,top,freq
certifications1,42,42,{'name': 'Psychology'},1
certifications10,3,3,"{'authority': 'LinkedIn', 'name': 'Project Man...",1
certifications2,21,21,"{'authority': 'OpenClassrooms', 'name': 'Learn...",1
certifications3,12,12,"{'authority': 'COLIBRIS', 'name': 'Quelle démo...",1
certifications4,7,7,"{'authority': 'A Cloud Guru', 'name': 'Introdu...",1
certifications5,6,6,"{'authority': 'Google', 'name': 'Google Ads Ce...",1
certifications6,6,6,"{'authority': 'Google', 'name': 'Certification...",1
certifications7,6,6,"{'authority': 'HubSpot', 'name': 'Hubspot Inbo...",1
certifications8,4,4,"{'authority': 'LinkedIn', 'name': 'Become an H...",1
certifications9,4,4,"{'authority': 'ETS Global', 'name': 'TOEIC', '...",1
education1,160,160,{'entityUrn': 'urn:li:fs_education:(ACoAAARi9f...,1
education2,144,144,{'entityUrn': 'urn:li:fs_education:(ACoAAApOhv...,1
education3,120,120,{'entityUrn': 'urn:li:fs_education:(ACoAAArChZ...,1
experience1,166,166,{'entityUrn': 'urn:li:fs_position:(ACoAAARi9fc...,1
experience2,161,161,{'entityUrn': 'urn:li:fs_position:(ACoAAARi9fc...,1
experience3,160,160,{'entityUrn': 'urn:li:fs_position:(ACoAAARi9fc...,1
experience4,156,156,"{'locationName': 'Paris', 'entityUrn': 'urn:li...",1
experience5,149,149,{'entityUrn': 'urn:li:fs_position:(ACoAAApOhv4...,1
geoCountryName,166,3,France,159
geoLocationName,141,37,"Paris, Île-de-France",58
headline,167,167,Web expert chez Jolicode,1
honors1,31,31,{'description': 'Innovators Under 35 is the le...,1
honors2,20,20,{'description': 'Léonore a été l'une des 10 en...,1
honors3,11,11,{'occupation': 'urn:li:fs_position:(ACoAAAf5iK...,1
honors4,9,9,{'description': 'Voxe a été intégré au program...,1
honors5,7,7,{'description': 'http://voxfemina.eu/actualite...,1
honors6,6,6,{'description': 'Le Google Impact Challenge Fr...,1
honors7,2,2,{'occupation': 'urn:li:fs_position:(ACoAAADaPF...,1
languages1,117,32,"{'name': 'English', 'proficiency': 'FULL_PROFE...",18
languages2,108,32,"{'name': 'French', 'proficiency': 'NATIVE_OR_B...",27
languages3,93,43,"{'name': 'Français', 'proficiency': 'NATIVE_OR...",32
languages4,49,34,"{'name': 'Français', 'proficiency': 'NATIVE_OR...",8
languages5,22,17,"{'name': 'Espagnol', 'proficiency': 'FULL_PROF...",2
languages6,7,7,"{'name': 'Spanish', 'proficiency': 'ELEMENTARY'}",1
languages7,2,2,"{'name': 'Italien', 'proficiency': 'ELEMENTARY'}",1
projects1,47,47,{'members': [{'member': {'firstName': 'Bastien...,1
projects2,31,31,{'members': [{'member': {'firstName': 'Bastien...,1
projects3,20,20,{'members': [{'member': {'firstName': 'Coline'...,1
projects4,14,14,{'occupation': 'urn:li:fs_position:(ACoAAABaH0...,1
projects5,10,10,{'occupation': 'urn:li:fs_position:(ACoAAABaH0...,1
projects6,4,4,{'occupation': 'urn:li:fs_position:(ACoAAAfEoR...,1
projects7,4,4,{'occupation': 'urn:li:fs_position:(ACoAAAfEoR...,1
projects8,1,1,{'occupation': 'urn:li:fs_position:(ACoAAAMqDL...,1
publications1,63,63,"{'date': {'month': 2, 'year': 2015, 'day': 3},...",1
publications10,13,13,"{'date': {'year': 2012}, 'name': '""Les Politiq...",1
publications2,46,46,"{'date': {'month': 5, 'year': 2017, 'day': 31}...",1
publications3,38,38,"{'date': {'month': 4, 'year': 2017, 'day': 20}...",1
publications4,37,37,"{'date': {'month': 6, 'year': 2008, 'day': 1},...",1
publications5,28,28,"{'date': {'month': 9, 'year': 2012, 'day': 24}...",1
publications6,25,25,"{'date': {'year': 2012}, 'name': 'Innovation p...",1
publications7,21,21,{'name': 'Mes Contributions dans le Huffington...,1
publications8,18,18,{'name': 'Mes contributions dans lePlus de l'O...,1
publications9,16,16,"{'date': {'year': 2013}, 'name': 'Qué Politica...",1
summary,107,107,"IT Consultant, Technical Expert, Lead develope...",1
volunteer1,75,75,"{'role': 'Administratrice', 'companyName': 'La...",1
volunteer2,63,63,"{'role': 'Présidente-fondatrice', 'companyName...",1
volunteer3,43,43,{'role': 'Dirigeante - Coach de l'équipe fémin...,1

### Exploding columns

In [16]:
# there must be a more functional way to do what is happening below
# but i'm too tired :)

In [17]:
for i in range (1,4): 
    data=pd.concat([data, 
    pd.DataFrame(data['education'+str(i)].apply(pd.Series)).add_prefix('ed_'+str(i)), 
    pd.DataFrame(data['volunteer'+str(i)].apply(pd.Series)).add_prefix('vol_'+str(i))], 
    axis=1).reset_index(drop=True)
    data.drop(columns=['education'+str(i),'volunteer'+str(i)], inplace=True)

In [18]:
for i in range (1,6): 
    data=pd.concat([data, 
    pd.DataFrame(data['experience'+str(i)].apply(pd.Series)).add_prefix('exp_'+str(i))], 
    axis=1).reset_index(drop=True)
    data.drop(columns='experience'+str(i), inplace=True)

In [19]:
for i in range (1,8): 
    data=pd.concat([data, 
    pd.DataFrame(data['honors'+str(i)].apply(pd.Series)).add_prefix('hon_'+str(i)), 
    pd.DataFrame(data['languages'+str(i)].apply(pd.Series)).add_prefix('lang_'+str(i))], 
    axis=1).reset_index(drop=True)
    data.drop(columns=['honors'+str(i),'languages'+str(i)], inplace=True)

In [20]:
for i in range (1,9): 
    data=pd.concat([data, 
    pd.DataFrame(data['projects'+str(i)].apply(pd.Series)).add_prefix('proj_'+str(i))], 
    axis=1).reset_index(drop=True)
    data.drop(columns='projects'+str(i), inplace=True)

In [21]:
for i in range (1,11): 
    data=pd.concat([data, 
    pd.DataFrame(data['certifications'+str(i)].apply(pd.Series)).add_prefix('cert_'+str(i)), 
    pd.DataFrame(data['publications'+str(i)].apply(pd.Series)).add_prefix('pub_'+str(i))], 
    axis=1).reset_index(drop=True)
    data.drop(columns=['certifications'+str(i),'publications'+str(i)], inplace=True)

In [22]:
list_columns=[i for i in data.columns if ("Urn" in i or "Logo" in i or "_region" in i or '_abuse' in i or '_geo' in i or '_proj' in i or '_organi' in i or '_0' in i)]
#to check before dropping 
#data[list_columns].T
data.drop(columns=list_columns, inplace=True)

### Dropping columns with too many missing values

In [23]:
a= list(data.columns)
a.sort()
data= data[a]

In [24]:
nullvalues=pd.DataFrame(data.isna().sum().sort_values(ascending=False))

In [25]:
print(list(nullvalues.index))

['cert_10', 'pub_20', 'ed_30', 'cert_40', 'lang_40', 'proj_10', 'exp_50', 'hon_30', 'hon_70', 'cert_50', 'proj_80', 'ed_20', 'cert_60', 'pub_10', 'pub_100', 'lang_70', 'ed_10', 'exp_30', 'cert_70', 'exp_40', 'lang_10', 'lang_60', 'lang_50', 'lang_20', 'lang_30', 'cert_90', 'cert_80', 'proj_70', 'hon_60', 'proj_20', 'vol_20', 'cert_100', 'pub_90', 'hon_20', 'pub_80', 'vol_30', 'cert_20', 'proj_30', 'proj_40', 'proj_60', 'hon_40', 'exp_10', 'pub_70', 'hon_10', 'exp_20', 'pub_60', 'pub_50', 'proj_50', 'hon_50', 'cert_30', 'pub_40', 'pub_30', 'vol_10', 'exp_2courses', 'exp_1courses', 'proj_8title', 'cert_9licenseNumber', 'proj_8url', 'proj_8timePeriod', 'proj_8occupation', 'proj_8members', 'proj_8description', 'proj_6occupation', 'exp_2organizations', 'exp_2honors', 'cert_8licenseNumber', 'exp_1projects', 'exp_5courses', 'cert_3licenseNumber', 'cert_10licenseNumber', 'hon_7description', 'cert_5licenseNumber', 'exp_4courses', 'exp_5organizations', 'cert_4licenseNumber', 'proj_6url', 'proj_7url', 'cert_5displaySource', 'hon_7issueDate', 'exp_2projects', 'lang_7proficiency', 'cert_5url', 'exp_5honors', 'cert_7licenseNumber', 'ed_3projects', 'exp_3courses', 'exp_3honors', 'cert_10displaySource', 'exp_1organizations', 'lang_7name', 'hon_7issuer', 'hon_7title', 'cert_10url', 'hon_7occupation', 'cert_6licenseNumber', 'ed_3honors', 'cert_10timePeriod', 'cert_2licenseNumber', 'exp_5projects', 'cert_10company', 'ed_3courses', 'cert_10authority', 'cert_10name', 'cert_8displaySource', 'cert_6displaySource', 'cert_9url', 'cert_8timePeriod', 'cert_8url', 'cert_7url', 'cert_7displaySource', 'cert_9displaySource', 'cert_6url', 'ed_2courses', 'proj_7occupation', 'exp_4honors', 'exp_3projects', 'proj_7timePeriod', 'ed_2honors', 'exp_4projects', 'hon_6occupation', 'hon_6description', 'proj_7title', 'ed_1honors', 'proj_6members', 'cert_9name', 'cert_9company', 'cert_9authority', 'proj_7members', 'proj_7description', 'proj_6title', 'proj_6timePeriod', 'proj_6description', 'cert_4displaySource', 'cert_3url', 'cert_3displaySource', 'cert_8name', 'cert_8company', 'cert_8authority', 'cert_4url', 'cert_9timePeriod', 'hon_6issuer', 'exp_1honors', 'ed_1courses', 'hon_6issueDate', 'ed_2projects', 'hon_5occupation', 'hon_5description', 'hon_4description', 'cert_4timePeriod', 'hon_6title', 'cert_6company', 'hon_5issueDate', 'cert_5authority', 'cert_5company', 'cert_5name', 'cert_5timePeriod', 'cert_6authority', 'cert_6name', 'cert_7name', 'pub_10description', 'cert_7timePeriod', 'hon_3description', 'cert_7company', 'cert_7authority', 'cert_6timePeriod', 'cert_2url', 'hon_5issuer', 'hon_4issuer', 'hon_5title', 'proj_5url', 'cert_4authority', 'cert_4company', 'ed_1projects', 'cert_4name', 'lang_6proficiency', 'lang_6name', 'cert_2displaySource', 'proj_5occupation', 'hon_4issueDate', 'hon_4occupation', 'pub_9description', 'proj_5timePeriod', 'proj_4occupation', 'hon_3occupation', 'hon_4title', 'hon_3issuer', 'cert_3timePeriod', 'pub_8description', 'proj_5description', 'proj_5title', 'proj_5members', 'hon_3title', 'pub_7description', 'proj_4url', 'hon_3issueDate', 'cert_3company', 'hon_2description', 'proj_3occupation', 'cert_3authority', 'cert_1licenseNumber', 'cert_3name', 'proj_3url', 'pub_10date', 'proj_4description', 'pub_10name', 'pub_10url', 'pub_5description', 'pub_10publisher', 'pub_10authors', 'ed_3activities', 'proj_4members', 'pub_6description', 'proj_4timePeriod', 'proj_4title', 'pub_9url', 'pub_9publisher', 'pub_9name', 'ed_1grade', 'pub_9date', 'pub_9authors', 'pub_8url', 'proj_2occupation', 'hon_2occupation', 'cert_2timePeriod', 'ed_2activities', 'cert_1url', 'pub_8date', 'pub_8publisher', 'cert_1displaySource', 'ed_3grade', 'pub_8authors', 'hon_2issuer', 'proj_3description', 'pub_8name', 'hon_1description', 'cert_2company', 'proj_3timePeriod', 'hon_2issueDate', 'pub_4description', 'hon_1occupation', 'proj_3title', 'ed_2grade', 'proj_3members', 'hon_2title', 'pub_7date', 'cert_2authority', 'pub_7publisher', 'pub_7authors', 'pub_7name', 'lang_5proficiency', 'proj_2url', 'cert_2name', 'pub_7url', 'lang_5name', 'pub_6publisher', 'pub_6url', 'proj_1occupation', 'pub_6date', 'pub_5publisher', 'pub_6authors', 'pub_6name', 'pub_5url', 'proj_2description', 'pub_3description', 'hon_1issuer', 'pub_5authors', 'pub_5name', 'pub_5date', 'vol_3description', 'pub_2description', 'proj_2timePeriod', 'hon_1issueDate', 'vol_3company', 'proj_2title', 'proj_2members', 'hon_1title', 'ed_1activities', 'vol_3cause', 'pub_4publisher', 'cert_1timePeriod', 'cert_1company', 'pub_3publisher', 'pub_4date', 'proj_1url', 'pub_4url', 'pub_3url', 'pub_4name', 'cert_1authority', 'pub_4authors', 'pub_3authors', 'ed_3description', 'pub_3date', 'pub_3name', 'vol_3timePeriod', 'ed_2description', 'proj_1description', 'vol_2description', 'pub_1description', 'cert_1name', 'pub_2publisher', 'vol_3role', 'vol_3companyName', 'pub_2date', 'pub_2url', 'lang_4proficiency', 'pub_2authors', 'pub_2name', 'vol_2company', 'proj_1members', 'proj_1timePeriod', 'proj_1title', 'lang_4name', 'ed_1description', 'vol_1description', 'vol_1company', 'pub_1publisher', 'vol_2cause', 'pub_1url', 'vol_1cause', 'pub_1date', 'vol_2timePeriod', 'vol_2role', 'pub_1name', 'vol_2companyName', 'pub_1authors', 'exp_4region', 'vol_1timePeriod', 'exp_5region', 'exp_2region', 'exp_3region', 'vol_1companyName', 'vol_1role', 'exp_1region', 'ed_3fieldOfStudy', 'lang_3proficiency', 'lang_3name', 'ed_3school', 'lang_1proficiency', 'exp_1description', 'lang_2proficiency', 'ed_3degreeName', 'exp_2description', 'summary', 'lang_2name', 'exp_3description', 'ed_3timePeriod', 'ed_2school', 'ed_2fieldOfStudy', 'exp_5description', 'lang_1name', 'ed_3schoolName', 'exp_5geoLocationName', 'exp_4description', 'exp_1geoLocationName', 'exp_1locationName', 'exp_5locationName', 'exp_4locationName', 'exp_4geoLocationName', 'ed_2degreeName', 'exp_2locationName', 'exp_2geoLocationName', 'exp_5company', 'ed_1fieldOfStudy', 'exp_3geoLocationName', 'exp_3locationName', 'exp_3company', 'exp_4company', 'exp_2company', 'ed_2timePeriod', 'geoLocationName', 'ed_1school', 'ed_1degreeName', 'ed_2schoolName', 'exp_5title', 'exp_5timePeriod', 'exp_5companyName', 'exp_1company', 'exp_4title', 'exp_4companyName', 'exp_4timePeriod', 'ed_1timePeriod', 'exp_3companyName', 'exp_3timePeriod', 'exp_3title', 'ed_1schoolName', 'exp_2title', 'exp_2timePeriod', 'exp_2companyName', 'exp_1timePeriod', 'exp_1companyName', 'exp_1title', 'geoCountryName', 'headline']

In [26]:
#columns= data.columns()
columnstodrop=[i for i in data.columns if data[i].isna().sum() > len(data)/2+10]
data.drop(columns=columnstodrop, inplace=True)

In [27]:
nullvalues=pd.DataFrame(data.isna().sum().sort_values(ascending=False))
nullvalues.head()

                   0
exp_2region       94
vol_1role         93
exp_3region       93
vol_1companyName  93
exp_1region       83

### Other recoding - could be improved

In [28]:
data.drop(columns=['ed_1school', 'ed_2school','ed_3school'], inplace=True)

#### Time columns could be split

In [29]:
timecols= [i for i in data.columns if "time" in i]
timecols

['ed_1timePeriod',
 'ed_2timePeriod',
 'ed_3timePeriod',
 'exp_1timePeriod',
 'exp_2timePeriod',
 'exp_3timePeriod',
 'exp_4timePeriod',
 'exp_5timePeriod']

In [30]:
#data.isna().sum()
data.fillna("[]", inplace=True)
# we are filling na with [] because special characters will be removed later on.

In [31]:
data.head(10)

,ed_1degreeName,ed_1fieldOfStudy,ed_1schoolName,ed_1timePeriod,ed_2degreeName,ed_2fieldOfStudy,ed_2schoolName,ed_2timePeriod,ed_3degreeName,ed_3fieldOfStudy,...,headline,lang_1name,lang_1proficiency,lang_2name,lang_2proficiency,lang_3name,lang_3proficiency,summary,vol_1companyName,vol_1role
0,Master informatique,Architecture logicielle distribuée,Université Bordeaux I,"{'endDate': {'year': 2009}, 'startDate': {'yea...",[],[],[],[],[],[],...,Web expert chez Jolicode,Anglais,[],[],[],[],[],"IT Consultant, Technical Expert, Lead develope...",[],[]
1,Master 2,Sciences politiques,Université Paris 1 Panthéon-Sorbonne,"{'endDate': {'year': 2007}, 'startDate': {'yea...",Licence,Droit,Université Lille 2 Droit et Santé,"{'endDate': {'year': 2005}, 'startDate': {'yea...",[],[],...,Directrice des opérations chez Cap Collectif,[],[],[],[],[],[],[],La Cravate Solidaire,Administratrice
2,Master's 2 Degree Marketing & Strategy - Inte...,[],Université Paris Dauphine,"{'endDate': {'year': 2015}, 'startDate': {'yea...",Postgraduate master’s degree in Information an...,[],Université Sorbonne Nouvelle (Paris III),"{'endDate': {'year': 2013}, 'startDate': {'yea...",Bachelor's degree,"Communication, rédaction et multimédia",...,"Regional Director (France, Italy, Russia and S...",Anglais,FULL_PROFESSIONAL,Espagnol,LIMITED_WORKING,Français,NATIVE_OR_BILINGUAL,People Power,Samu Social de Paris,Volunteer
3,Masters Degree,Written & Audiovisual Journalism,Université libre de Bruxelles,"{'endDate': {'year': 2006}, 'startDate': {'yea...",Creating Collaborative Solutions,Political Science and Government,Harvard Kennedy School,"{'endDate': {'year': 2017}, 'startDate': {'yea...",9 weeks full stack bootcamp,Computer Science,...,Co-founder & CEO @Fluicity 💡 Co-founder Associ...,Arabic,LIMITED_WORKING,English,[],French,NATIVE_OR_BILINGUAL,16+ years of experience driving change in the ...,BeCode.org,Board Member
4,"Master of management, organisations and govern...",[],The London School of Economics and Political S...,"{'endDate': {'year': 2009}, 'startDate': {'yea...",[],[],Institut National des Etudes Territoriales (INET),"{'endDate': {'year': 2011}, 'startDate': {'yea...",Master Affaires Publiques,[],...,Directrice générale adjointe chez Adie,Anglais,PROFESSIONAL_WORKING,Français,NATIVE_OR_BILINGUAL,[],[],[],[],[]
5,MBA,Strategy,ESSEC - ESSEC Business School,"{'endDate': {'year': 2006}, 'startDate': {'yea...",Master of Business Administration (MBA),Strategy and organisation,ESSEC - ESSEC Business School,"{'endDate': {'year': 2006}, 'startDate': {'yea...",Master of Business Administration - MBA,[],...,Directeur Associé - Chief Revenue Officer (CRO...,[],[],[],[],[],[],"17 ans d'expérience, intelligence collective, ...",[],[]
6,Master 2,Management des Ressources Humaines,"Pantheon ASSAS University, Paris","{'endDate': {'year': 2005}, 'startDate': {'yea...",[],[],[],[],[],[],...,CEO & Co-founder at Civocracy\n!We are hiring!,Chinese,PROFESSIONAL_WORKING,English,FULL_PROFESSIONAL,French,NATIVE_OR_BILINGUAL,After eight years of social entrepreneurship i...,[],[]
7,Masters,International Politics,Sciences Po Bordeaux,"{'endDate': {'year': 2010}, 'startDate': {'yea...",Social entrepreneurship summer training,"Business Administration and Management, General",University of Cambridge,"{'endDate': {'year': 2015}, 'startDate': {'yea...",Licenciatura,Ciencias Politicas y de la Administracion,...,#onrecrute - CEO de Voxe média-école d'empower...,English,NATIVE_OR_BILINGUAL,French,NATIVE_OR_BILINGUAL,Spanish,NATIVE_OR_BILINGUAL,Experienced Chief Executive Officer with a dem...,Empow'Her,Mentor du programme Woman'Act
8,Dut SRC,[],Université de Caen Basse Normandie,[],[],[],Université du Maine-Le Mans-Laval,[],[],[],...,"Directeur Technique chez Monsieur SLOOP, ABCDE...",[],[],[],[],[],[],[],[],[]
9,Start-up Launchpad,Master of Digital Business,HEC Paris,"{'endDate': {'year': 2017}, 'startDate': {'yea...",Master's degree,Public affairs and management,Sciences Po Lille,"{'endDate': {'year': 2016}, 'startDate': {'yea...",Bachelor,Law,...,Belgium France @Sdui | Tech-For-Good Leader & ...,[],[],[],[],[],[],Drawing on 7 years of experience as a Team Lea...,Anacej,Vice-Président

In [32]:
data.shape

(168, 62)

### Make dataframe with described dataset (modes, counts...) - not interesting if the dataframe is at this level of transformation

In [33]:
#data.describe().T
#general_pop_data= pd.DataFrame(data.describe(include="O").T)
#general_pop_data.to_csv("general_pop_data.csv", sep=';')

In [34]:
pd.options.display.max_rows = 100
data.head(5).T

,0,1,2,3,4
ed_1degreeName,Master informatique,Master 2,Master's 2 Degree Marketing & Strategy - Inte...,Masters Degree,"Master of management, organisations and govern..."
ed_1fieldOfStudy,Architecture logicielle distribuée,Sciences politiques,[],Written & Audiovisual Journalism,[]
ed_1schoolName,Université Bordeaux I,Université Paris 1 Panthéon-Sorbonne,Université Paris Dauphine,Université libre de Bruxelles,The London School of Economics and Political S...
ed_1timePeriod,"{'endDate': {'year': 2009}, 'startDate': {'yea...","{'endDate': {'year': 2007}, 'startDate': {'yea...","{'endDate': {'year': 2015}, 'startDate': {'yea...","{'endDate': {'year': 2006}, 'startDate': {'yea...","{'endDate': {'year': 2009}, 'startDate': {'yea..."
ed_2degreeName,[],Licence,Postgraduate master’s degree in Information an...,Creating Collaborative Solutions,[]
ed_2fieldOfStudy,[],Droit,[],Political Science and Government,[]
ed_2schoolName,[],Université Lille 2 Droit et Santé,Université Sorbonne Nouvelle (Paris III),Harvard Kennedy School,Institut National des Etudes Territoriales (INET)
ed_2timePeriod,[],"{'endDate': {'year': 2005}, 'startDate': {'yea...","{'endDate': {'year': 2013}, 'startDate': {'yea...","{'endDate': {'year': 2017}, 'startDate': {'yea...","{'endDate': {'year': 2011}, 'startDate': {'yea..."
ed_3degreeName,[],[],Bachelor's degree,9 weeks full stack bootcamp,Master Affaires Publiques
ed_3fieldOfStudy,[],[],"Communication, rédaction et multimédia",Computer Science,[]
ed_3schoolName,[],[],Université de Sherbrooke / Sherbrooke University,Le Wagon,Sciences Po
ed_3timePeriod,[],[],"{'endDate': {'year': 2012}, 'startDate': {'yea...","{'endDate': {'year': 2014}, 'startDate': {'yea...","{'endDate': {'year': 2008}, 'startDate': {'yea..."
exp_1company,[],"{'employeeCountRange': {'start': 11, 'end': 50...","{'employeeCountRange': {'start': 201, 'end': 5...","{'employeeCountRange': {'start': 2, 'end': 10}...","{'employeeCountRange': {'start': 501, 'end': 1..."
exp_1companyName,Jolicode,Cap Collectif,Change.org,Fluicity,Adie
exp_1description,I co-created JoliCode in march 2012 in order t...,"Pilotage des activités des pôles conseil, comm...",[],Fluicity provides government agencies with col...,[]
exp_1geoLocationName,[],[],"Paris, Île-de-France, France","Paris Area, France",[]
exp_1locationName,[],[],"Paris, Île-de-France, France","Paris Area, France",[]
exp_1region,[],[],"urn:li:fs_region:(fr,0)","urn:li:fs_region:(fr,5227)",[]
exp_1timePeriod,"{'startDate': {'month': 3, 'year': 2012}}","{'startDate': {'month': 3, 'year': 2022}}","{'startDate': {'month': 9, 'year': 2022}}","{'startDate': {'month': 1, 'year': 2015}}","{'startDate': {'month': 9, 'year': 2020}}"
exp_1title,Web expert,Directrice des opérations,"Regional Director( France, Italy, Russia, Spain)",Co-Founder & CEO,Directrice générale adjointe
exp_2company,"{'employeeCountRange': {'start': 201, 'end': 5...","{'employeeCountRange': {'start': 11, 'end': 50...","{'employeeCountRange': {'start': 0, 'end': 1},...","{'employeeCountRange': {'start': 10001}, 'indu...","{'employeeCountRange': {'start': 501, 'end': 1..."
exp_2companyName,Clever Age,Cap Collectif,Maison Bonnemuse,Google,Adie
exp_2description,"Expert PHP : audit, performance, méthodologie ...","Key figures : 250 clients / 2,5 M€ CA / 30 ETP...",Sustainable and inclusive jumpsuits that tell ...,Responsibilities:\n- Drive platforms revenue g...,[]
exp_2geoLocationName,[],[],"Paris, Île-de-France, France","Istanbul, Dubai","Région de Paris, France"
exp_2locationName,[],[],"Paris, Île-de-France, France","Istanbul, Dubai","Région de Paris, France"
exp_2region,[],[],"urn:li:fs_region:(fr,0)",[],[]
exp_2timePeriod,"{'endDate': {'month': 1, 'year': 2012}, 'start...","{'endDate': {'month': 3, 'year': 2022}, 'start...","{'startDate': {'month': 10, 'year': 2020}}","{'endDate': {'month': 7, 'year': 2015}, 'start...","{'startDate': {'month': 9, 'year': 2019}}"
exp_2title,Consultant Expert PHP,Directrice du développement commercial,Founder,"Regional Sales Manager, Media Platforms, MENA ...",Directrice des relations institutionnelles et ...
exp_3company,[],"{'employeeCountRange': {'start': 11, 'end': 50...","{'employeeCountRange': {'start': 201, 'end': 5...","{'employeeCountRange': {'start': 10001}, 'indu...","{'employeeCountRange': {'start': 2, 'end': 10}..."
exp_3companyName,Solution Interactive,Animafac,Change.org,Google,FLUICITY
exp_3description,[],Pilotage du projet associatif et des plaidoyer...,[],Responsibilities:\n- Build and execute market ...,Start up de la Civic Tech. Plateforme numériq...
exp_3geoLocationName,[],Paris,"Paris, Île-de-France, France","Paris, Emerging markets (covering AE, IL, PL, ...","Région de Paris, France"
exp_3locationName,[],Paris,"Paris, Île-de-France, France","Paris, Emerging markets (covering AE, IL, PL, ...","Région de Paris, France"
exp_3region,[],[],"urn:li:fs_region:(fr,0)",[],"urn:li:fs_region:(fr,5227)"
exp_3timePeriod,"{'endDate': {'month': 9, 'year': 2009}, 'start...","{'endDate': {'month': 1, 'year': 2017}, 'start...","{'endDate': {'month': 10, 'year': 2022}, 'star...","{'endDate': {'month': 12, 'year': 2012}, 'star...","{'endDate': {'month': 5, 'year': 2019}, 'start..."
exp_3title,Lead developer,Déléguée générale,"Director, France and Campaigns Support","Senior Sales Manager, Media Platforms, Emergin...",Responsable du développement
exp_4company,[],"{'employeeCountRange': {'start': 11, 'end': 50...","{'employeeCountRange': {'start': 201, 'end': 5...","{'employeeCountRange': {'start': 2, 'end': 10}...","{'employeeCountRange': {'start': 10001}, 'indu..."
exp_4companyName,[],Animafac,Change.org,Unfair magazine,Mairie de Paris
exp_4description,[],[],Senior campaigner in charge of looking ahead a...,Launched and established the first Abu Dhabi b...,"Insertion sociale et professionnelle (RSA), in..."
exp_4geoLocationName,[],Paris,"Paris Area, France","Abu Dhabi, United Arab Emirates","Région de Paris, France"
exp_4locationName,[],Paris,"Paris Area, France","Abu Dhabi, United Arab Emirates","Région de Paris, France"
exp_4timePeriod,[],"{'endDate': {'month': 9, 'year': 2012}, 'start...","{'endDate': {'month': 12, 'year': 2020}, 'star...","{'endDate': {'month': 9, 'year': 2010}, 'start...","{'endDate': {'month': 12, 'year': 2016}, 'star..."
exp_4title,[],Directrice administrative et financière,Senior Campaigner,Managing Director,Adjointe de la sous directrice en charge de l'...
exp_5company,[],"{'employeeCountRange': {'start': 10001}, 'indu...","{'employeeCountRange': {'start': 201, 'end': 5...","{'employeeCountRange': {'start': 10001}, 'indu...","{'employeeCountRange': {'start': 5001, 'end': ..."
exp_5companyName,[],Mairie de Paris,Change.org,BBC News,Conseil Général du Nord
exp_5description,[],[],[],Responsibilities:\n- Produce Middle East Busin...,Mise en place d’une démarche globale de suivi ...
exp_5geoLocationName,[],[],"Paris Area, France","Dubai, United Arab Emirates",[]
exp_5locationName,[],[],"Paris Area, France","Dubai, United Arab Emirates",[]
exp_5timePeriod,[],"{'endDate': {'year': 2009}, 'startDate': {'yea...","{'endDate': {'month': 5, 'year': 2018}, 'start...","{'endDate': {'month': 12, 'year': 2008}, 'star...","{'endDate': {'month': 10, 'year': 2014}, 'star..."
exp_5title,[],Chargée de mission auprès du chef de cabinet d...,Campaigner,Producer,Responsable de service
geoCountryName,France,France,France,France,France
geoLocationName,Greater Paris Metropolitan Region,Greater Paris Metropolitan Region,"Paris, Île-de-France","Paris, Île-de-France","Montreuil, Île-de-France"
headline,Web expert chez Jolicode,Directrice des opérations chez Cap Collectif,"Regional Director (France, Italy, Russia and S...",Co-founder & CEO @Fluicity 💡 Co-founder Associ...,Directrice générale adjointe chez Adie
lang_1name,Anglais,[],Anglais,Arabic,Anglais
lang_1proficiency,[],[],FULL_PROFESSIONAL,LIMITED_WORKING,PROFESSIONAL_WORKING
lang_2name,[],[],Espagnol,English,Français
lang_2proficiency,[],[],LIMITED_WORKING,[],NATIVE_OR_BILINGUAL
lang_3name,[],[],Français,French,[]
lang_3proficiency,[],[],NATIVE_OR_BILINGUAL,NATIVE_OR_BILINGUAL,[]
summary,"IT Consultant, Technical Expert, Lead develope...",[],People Power,16+ years of experience driving change in the ...,[]
vol_1companyName,[],La Cravate Solidaire,Samu Social de Paris,BeCode.org,[]
vol_1role,[],Administratrice,Volunteer,Board Member,[]

### Exporting our dataset

In [35]:
data.to_csv("dataset2.csv", sep=';', index=False)